Repository FC-Mini-Project-6/Mini-Project-6-FE, pull requests merged in 2023-02, with the labels that each got.

#12 [#8] Feat: 회원가입 페이지 마크업
  package-lock.json
  package.json
  src/main.tsx
  src/pages/SignInPage/OptionalInfo.tsx
  src/pages/SignInPage/index.tsx
  src/pages/SignUpPage/index.tsx
  tailwind.config.cjs
Labels: feature

#13 [#9] Style: 장바구니 기본 마크업
  .idea/.gitignore
  .idea/Mini-Project-6-FE.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/vcs.xml
  src/assets/008.png
  src/assets/Vector.svg
  src/pages/CartNLikesPage/components/CartItem.tsx
  src/pages/CartNLikesPage/index.tsx
Labels: good first issue, feature

#14 [#7] Feat: 메인페이지 개발중
  package-lock.json
  package.json
  src/App.tsx
  src/components/Header.tsx
  src/components/MainPage/GoodsList.tsx
  src/components/MainPage/ListBox.tsx
  src/components/MainPage/RecommendList.tsx
  src/pages/MainPage/index.tsx
  src/slider/slick.tsx
Labels: good first issue, feature

#16 [#5] Feat: 마이 페이지 마크업 & 헤더 CSS 수정
  index.html
  public/favicon.ico
  public/images/미왕이1.png
  public/images/미왕이2.png
  public/images/미왕이3.png
  public/images/미왕이4.png
  src/components/Header.tsx
  src/pages/MyPage/index.tsx
Labels: feature

#18 [#17] Feat: 상품 상세 페이지 마크업
  src/components/InfoSelect.tsx
  src/main.tsx
  src/pages/LoanDetailPage/index.tsx
  src/pages/ProductDetail/index.tsx
  src/pages/SignInPage/OptionalInfo.tsx
  src/pages/SignInPage/index.tsx
  src/pages/SignUpPage/index.tsx
Labels: feature

#20 [#7] Feat: 메인페이지 개발
  src/assets/index.css
  src/components/Header.tsx
  src/components/MainPage/GoodsList.tsx
  src/components/MainPage/ListBox.tsx
  src/components/MainPage/RecommendList.tsx
  src/slider/slick.tsx
Labels: feature

#21 [#5] Feat: 이용 중인 대출 페이지 마크업 (진행 중)
  src/components/Header.tsx
  src/components/MyPage/LoanBox.tsx
  src/components/UserLoan/AccountDetail.tsx
  src/components/UserLoan/AccountHistory.tsx
  src/main.tsx
  src/pages/MyPage/index.tsx
  src/pages/UserLoanPage/index.tsx
Labels: bug, feature

#23 [#22] Fix: 헤더 컴포넌트 클래스명 수정
  src/components/Header.tsx
Labels: bug, feature

#24 [#5] Feat: 마이 페이지 마크업
  src/components/UserLoan/AccountDetail.tsx
  src/components/UserLoan/AccountHistory.tsx
  src/pages/UserInfoPage/index.tsx
  src/pages/UserLoanPage/index.tsx
Labels: feature

#26 [#5] Feat: 마이 페이지 마크업 & 헤더 마크업
  src/assets/index.css
  src/components/Header.tsx
  src/components/UserLoan/AccountHistory.tsx
  src/pages/MyPage/index.tsx
  src/pages/UserLoanPage/index.tsx
Labels: feature

#29 [#28] Feat: 회원가입 API 작성
  package-lock.json
  package.json
  src/api/axios.ts
  src/api/core/api.ts
  src/main.tsx
  src/pages/ProductDetail/index.tsx
  src/pages/SignInPage/index.tsx
  src/pages/SignUpPage/OptionalInfo.tsx
  src/pages/SignUpPage/index.tsx
  src/utils/age.ts
  src/utils/banks.ts
  src/utils/jobs.ts
  src/utils/regions.ts
  tailwind.config.cjs
Labels: feature

#33 [#31] 로그인 API 연결
  package-lock.json
  package.json
  src/api/axios.ts
  src/app/hooks.ts
  src/app/store.ts
  src/features/authSlice.ts
  src/main.tsx
  src/pages/SignInPage/index.tsx
  src/pages/SignUpPage/index.tsx
Labels: feature

#39 [#32] Feat: 마이 페이지 관심 상품 정보 & 회원 추가 정보 API 연결
  src/App.tsx
  src/api/axios.ts
  src/assets/index.css
  src/components/InfoSelect.tsx
  src/components/MyPage/LikeBox.tsx
  src/pages/MyPage/index.tsx
  src/pages/SignUpPage/OptionalInfo.tsx
  src/pages/UserInfoPage/index.tsx
  src/utils/jobs.ts
Labels: feature

#41 [#36] Feat: 장바구니 조회 api 연결
  src/api/axios.ts
  src/assets/loading/loading-bg.jpg
  src/assets/loading/loading1.svg
  src/assets/loading/loading2.svg
  src/assets/loading/loading3.svg
  src/assets/loading/loading4.svg
  src/pages/CartNLikesPage/components/CartItem.tsx
  src/pages/CartNLikesPage/index.tsx
  src/pages/LoadingPage/index.tsx
  tailwind.config.cjs
  vite.config.ts.timestamp-1676615689699.mjs
  yarn.lock
Labels: feature

#43 [#27, #32] Feat: 회원 정보 수정 페이지 API 연결 및 마크업 수정
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/api/axios.ts
  src/api/core/api.ts
  src/components/InfoSelect.tsx
  src/components/MyPage/LikeBox.tsx
  src/components/MyPage/TestLoading.tsx
  src/main.tsx
  src/pages/MyPage/index.tsx
  src/pages/UserInfoPage/index.tsx
  src/utils/crdtGrade.ts
  yarn.lock
Labels: feature

#44 [#42] 상품 상세 페이지 API 연결
  src/api/axios.ts
  src/components/ProductDetail/Etc.tsx
  src/components/ProductDetail/Loan.tsx
  src/components/ProductDetail/Target.tsx
  src/main.tsx
  src/pages/ProductDetail/index.tsx
  src/pages/SignUpPage/OptionalInfo.tsx
  src/pages/UserInfoPage/index.tsx
  src/utils/age.ts
  src/utils/banks.ts
  src/utils/infoData.ts
  src/utils/jobs.ts
  src/utils/regions.ts
Labels: feature

#45 [#27] Feat: 전체 페이지 로딩 페이지 생성
  package-lock.json
  package.json
  src/App.tsx
  src/components/MyPage/LoanBox.tsx
  src/main.tsx
  src/pages/CartNLikesPage/index.tsx
  src/pages/MyPage/index.tsx
  vite.config.ts
  yarn.lock
Labels: feature

#46 [#27] Feat: 마이페이지 CSS 수정
  src/components/InfoSelect.tsx
  src/components/MyPage/LikeBox.tsx
  src/pages/MyPage/index.tsx
  src/pages/SignUpPage/OptionalInfo.tsx
  src/pages/UserInfoPage/index.tsx
  src/utils/crdtGrade.ts
  src/utils/infoData.ts
Labels: feature

#50 [#42] Feat: 상품상세 페이지 컴포넌트 분리 중
  src/components/ProductDetail/Etc.tsx
  src/components/ProductDetail/Loan.tsx
  src/pages/ProductDetail/index.tsx
  src/pages/SignInPage/index.tsx
  src/pages/SignUpPage/OptionalInfo.tsx
  src/pages/SignUpPage/index.tsx
Labels: feature

#51 [#32, 42, 49] Feat: 회원 정보 페이지, 상품 상세 페이지
  src/api/axios.ts
  src/components/InfoSelect.tsx
  src/components/MyPage/TestLoading.tsx
  src/components/ProductDetail/Loan.tsx
  src/components/UserInfoPage/UserDetail.tsx
  src/components/UserInfoPage/UserInfo.tsx
  src/main.tsx
  src/pages/LoadingPage/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/ProductDetail/index.tsx
  src/pages/UserInfoPage/PasswordCheck.tsx
  src/pages/UserInfoPage/index.tsx
Labels: bug, feature

#52 [#48] Feat: 상품 상세 컴포넌트 분리, 타입 수정
  src/components/ProductDetail/Etc.tsx
  src/components/ProductDetail/Loan.tsx
  src/components/ProductDetail/Target.tsx
  src/pages/ProductDetail/index.tsx
Labels: feature

#56 [#47][#7] Feat: 메인페이지 api 연결 및 메뉴토글 작업
  public/images/NeedLogin.svg
  public/images/Users.png
  src/api/axios.ts
  src/api/core/api.ts
  src/components/Header.tsx
  src/components/MainPage/GoodsList.tsx
  src/components/MainPage/RecommendList.tsx
  src/components/MainPage/ToggleMenu/Agency.tsx
  src/components/MainPage/ToggleMenu/Location.tsx
  src/components/MainPage/ToggleMenu/Target.tsx
  src/components/MainPage/ToggleMenu/ToggleBody.tsx
  src/components/MainPage/ToggleMenu/ToggleHeader.tsx
  src/components/MainPage/ToggleMenu/Using.tsx
  src/components/MenuBar.tsx
  src/pages/MainPage/index.tsx
  yarn.lock
Labels: feature

#60 [#7][#48] 메인페이지 개발
  src/api/axios.ts
  src/api/core/api.ts
  src/components/MainPage/GoodsList.tsx
  src/components/MainPage/ListBox.tsx
  src/components/MainPage/RecommendList.tsx
  src/components/MainPage/ToggleMenu/Agency.tsx
  src/components/MainPage/ToggleMenu/Location.tsx
  src/components/MainPage/ToggleMenu/Target.tsx
  src/components/MainPage/ToggleMenu/ToggleBody.tsx
  src/components/MainPage/ToggleMenu/Using.tsx
  src/components/ProductDetail/Etc.tsx
  src/components/ProductDetail/Loan.tsx
  src/components/ProductDetail/Target.tsx
  src/main.tsx
  src/pages/ProductDetail/Etc.tsx
  src/pages/ProductDetail/Loan.tsx
  src/pages/ProductDetail/Target.tsx
  src/pages/allProduct/index.tsx
  src/utils/infoData.ts
  yarn.lock
Labels: feature

#61 Test: axios 설정 테스트
  README.md
  index.html
  src/api/axios.ts
  src/api/core/api.ts
  src/components/MenuBar2.tsx
  src/components/UserInfoPage/UserInfo.tsx
  src/pages/MyPage/index.tsx
  src/pages/UserInfoPage/PasswordCheck.tsx
  src/utils/Types.ts
Labels: docs, feature

#62 [#28] Feat: 회원 가입 성공시 로그인 화면으로 설정
  src/api/axios.ts
  src/components/ProductDetail/Target.tsx
  src/pages/ProductDetail/index.tsx
  src/pages/ProductDetail/interface.ts
  src/pages/SignInPage/index.tsx
  src/pages/SignUpPage/index.tsx
Labels: feature

#63 [#47] Feat: 로그인 시 토큰 값 저장 방식
  src/api/axios.ts
  src/api/core/api.ts
  src/pages/SignInPage/index.tsx
Labels: feature

#64 Style: axios.ts에 있는 코드 스타일 변경
  src/api/axios.ts
  src/pages/MyPage/index.tsx
Labels: bug, feature

#66 Style: axios.ts 코드 수정
  src/api/axios.ts
  src/api/core/api.ts
  src/components/MainPage/RecommendList.tsx
  src/components/MyPage/LikeBox.tsx
  src/components/UserInfoPage/UserDetail.tsx
  src/components/UserInfoPage/UserInfo.tsx
  src/pages/ProductDetail/index.tsx
  src/pages/UserInfoPage/PasswordCheck.tsx
Labels: bug

#65 [#48] Feat: 토큰으로 로그인 여부 판단 코드
  src/api/core/api.ts
  src/assets/index.css
  src/components/MainPage/RecommendList.tsx
  src/components/MainPage/ToggleMenu/ToggleHeader.tsx
  src/slider/slick.tsx
Labels: feature

#67 Feat: 쿠키 사용하여 토큰 값 저장하는 함수 정리
  src/api/core/api.ts
  src/pages/SignInPage/index.tsx
  src/utils/cookieFn.ts
Labels: feature

#68 [#7] Fix: 메인페이지 오류 수정
  src/api/axios.ts
  src/components/MainPage/GoodsList.tsx
  src/components/MainPage/RecommendList.tsx
Labels: feature

#69 [#32] Feat: 회원 정보 수정 페이지 api 연결 및 코드 정리
  src/api/axios.ts
  src/api/core/api.ts
  src/components/InfoSelect.tsx
  src/components/MyPage/LikeBox.tsx
  src/components/UserInfoPage/UserDetail.tsx
  src/components/UserInfoPage/UserInfo.tsx
  src/pages/MyPage/index.tsx
  src/pages/UserInfoPage/PasswordCheck.tsx
  src/utils/cookieFn.ts
Labels: feature

#71 [#70] Feat: 404페이지 마크업
  src/assets/meewang3.png
  src/main.tsx
  src/pages/NotFound/index.tsx
  src/pages/ProductDetail/Etc.tsx
  src/pages/ProductDetail/index.tsx
Labels: feature

#76 [#75] Feat: 토글 메뉴에 로그아웃 기능
  package-lock.json
  package.json
  src/api/axios.ts
  src/components/MainPage/GoodsList.tsx
  src/components/MainPage/RecommendList.tsx
  src/components/MainPage/ToggleMenu/ToggleHeader.tsx
  src/features/authSlice.ts
  src/pages/MainPage/index.tsx
  src/pages/allProduct/index.tsx
  src/utils/cookieFn.ts
  yarn.lock
Labels: feature

#78 [#58] Feat: 카테고리별 정보 나타내기
  src/api/axios.ts
  src/components/MainPage/ListBox.tsx
  src/components/MainPage/RecommendList.tsx
  src/components/MainPage/ToggleMenu/Agency.tsx
  src/components/MainPage/ToggleMenu/Location.tsx
  src/components/MainPage/ToggleMenu/Target.tsx
  src/components/MainPage/ToggleMenu/ToggleBody.tsx
  src/components/MainPage/ToggleMenu/ToggleHeader.tsx
  src/components/MainPage/ToggleMenu/Using.tsx
  src/main.tsx
  src/pages/CategoryPage/index.tsx
  src/utils/infoData.ts
Labels: feature

#80 [#48] 전체상품페이지 api 연결 및 페이지네이션 구현
  package-lock.json
  package.json
  src/api/axios.ts
  src/assets/paging.css
  src/components/MainPage/RecommendList.tsx
  src/components/MainPage/ToggleMenu/ToggleHeader.tsx
  src/pages/allProduct/index.tsx
  yarn.lock
Labels: feature

#82 [#72] Feat: redux 활용한 목록관리 및 createAsyncThunk
  .eslintrc.cjs
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/prettier.xml
  src/App.tsx
  src/api/axios.ts
  src/app/store.ts
  src/components/CartNLikePage/CarList.tsx
  src/features/cartSlice.ts
  src/pages/CartNLikesPage/index.tsx
  vite.config.ts.timestamp-1677142779145.mjs
  yarn.lock
Labels: feature

#83 [#79] Feat: 키워드 검색 구현 및 CSS 수정
  .eslintrc.cjs
  src/api/axios.ts
  src/components/MainPage/GoodsList.tsx
  src/components/MainPage/ListBox.tsx
  src/components/MainPage/RecommendList.tsx
  src/components/MainPage/ToggleMenu/ToggleHeader.tsx
  src/main.tsx
  src/pages/CategoryPage/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/ProductDetail/Etc.tsx
  src/pages/SearchPage/index.tsx
  vite.config.ts.timestamp-1676615689699.mjs
  vite.config.ts.timestamp-1677142779145.mjs
  yarn.lock
Labels: feature

#84 [#75] Feat: 로그인 여부에 따라 제한접근
  public/images/Users.svg
  src/components/MainPage/RecommendList.tsx
  src/components/MainPage/ToggleMenu/ToggleHeader.tsx
  src/main.tsx
  src/pages/CartNLikesPage/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/allProduct/index.tsx
Labels: feature

#85 [#79] Feat: 무한 스크롤 대신 페이징 구현
  package-lock.json
  package.json
  src/api/axios.ts
  src/components/MainPage/ToggleMenu/ToggleHeader.tsx
  src/main.tsx
  src/pages/CategoryPage/index.tsx
  src/pages/SearchPage/index.tsx
Labels: feature

#88 [#32] Feat: 마이 페이지 관심 상품 컴포넌트 수정
  src/api/axios.ts
  src/assets/index.css
  src/components/MyPage/LikeBox.tsx
  src/pages/MyPage/index.tsx
Labels: feature

#90 [#89] Feat: 회원가입 오류시 메세지를 토스트로 출력
  src/api/axios.ts
  src/api/core/api.ts
  src/components/ProductDetail/Etc.tsx
  src/pages/NotFound/index.tsx
  src/pages/ProductDetail/Etc.tsx
  src/pages/ProductDetail/Loan.tsx
  src/pages/ProductDetail/Target.tsx
  src/pages/ProductDetail/index.tsx
  src/pages/SignInPage/index.tsx
  src/pages/SignUpPage/index.tsx
Labels: feature

#91 [#48] [#79] Feat: 메인페이지 작업
  src/components/Header.tsx
  src/components/MainPage/RecommendList.tsx
  src/components/MainPage/ToggleMenu/ToggleHeader.tsx
  src/slider/slick.tsx
Labels: feature

#93 [#79] Feat: 장바구니, 관심 목록 토스트 띄우기
  src/components/MainPage/GoodsList.tsx
  src/components/MainPage/ListBox.tsx
  src/components/MyPage/LikeBox.tsx
  src/pages/CategoryPage/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/SearchPage/index.tsx
  src/pages/allProduct/index.tsx
  src/utils/cookieFn.ts
  src/utils/toasstify.ts
Labels: feature

#94 [#92] Feat: 토글 스타일링 수정
  src/components/MainPage/ToggleMenu/Agency.tsx
  src/components/MainPage/ToggleMenu/Location.tsx
  src/components/MainPage/ToggleMenu/Target.tsx
  src/components/MainPage/ToggleMenu/ToggleBody.tsx
  src/components/MainPage/ToggleMenu/Using.tsx
Labels: feature

#96 Docs: README.md 수정
  README.md
  images/allproduct.gif
  images/cart.png
  images/cartfavor.gif
  images/category.gif
  images/favor-1.gif
  images/loading.gif
  images/login-1.gif
  images/login-2.gif
  images/main-1.png
  images/main-2.png
  images/pwtest.gif
  images/search.gif
  images/toast-1.gif
  src/pages/SignInPage/index.tsx
  src/utils/Types.ts
Labels: docs, feature

#101 Docs: README.md 수정 & Feat: 상세, 장바구니 페이지 토스트 생성
  README.md
  images/detail.gif
  src/components/CartNLikePage/CarList.tsx
  src/components/CartNLikePage/CartItem.tsx
  src/pages/ProductDetail/index.tsx
Labels: docs, feature

#106 [#87] Feat: 로그인 실패시 토스트 띄우기
  src/api/axios.ts
  src/pages/SignInPage/index.tsx
Labels: feature

#107 [#25, 58] Feat: 메뉴바, 검색 페이지
  src/App.tsx
  src/components/MenuBar.tsx
  src/components/MenuBar2.tsx
  src/pages/SearchPage/index.tsx
Labels: bug, feature

#108 Feat: 로그인, 전체, 검색 페이지 수정
  src/App.tsx
  src/api/axios.ts
  src/components/MenuBar.tsx
  src/components/MenuBar2.tsx
  src/pages/SearchPage/index.tsx
  src/pages/SignInPage/index.tsx
Labels: feature

#109 Style: 코드 정리 / Feat: 회원 정보 수정 토스트 변경
  src/App.tsx
  src/api/axios.ts
  src/assets/Vector.svg
  src/assets/index.css
  src/assets/react.svg
  src/components/CartNLikePage/CartItem.tsx
  src/components/Header.tsx
  src/components/InfoSelect.tsx
  src/components/MainPage/GoodsList.tsx
  src/components/MainPage/ListBox.tsx
  src/components/MainPage/RecommendList.tsx
  src/components/MainPage/ToggleMenu/Agency.tsx
  src/components/MainPage/ToggleMenu/Location.tsx
  src/components/MainPage/ToggleMenu/Target.tsx
  src/components/MainPage/ToggleMenu/ToggleBody.tsx
  src/components/MainPage/ToggleMenu/ToggleHeader.tsx
  src/components/MainPage/ToggleMenu/Using.tsx
  src/components/MenuBar.tsx
  src/components/MyPage/LikeBox.tsx
  src/components/MyPage/LoanBox.tsx
  src/components/ProductDetail/Loan.tsx
  src/components/UserInfoPage/UserDetail.tsx
  src/components/UserInfoPage/UserInfo.tsx
  src/components/UserLoan/AccountDetail.tsx
  src/components/UserLoan/AccountHistory.tsx
  src/main.tsx
  src/pages/CartNLikesPage/index.tsx
  src/pages/CategoryPage/index.tsx
  src/pages/LoadingPage/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/SearchPage/index.tsx
  src/pages/SignInPage/index.tsx
  src/pages/SignUpPage/index.tsx
  src/pages/UserInfoPage/PasswordCheck.tsx
  src/pages/UserInfoPage/index.tsx
  src/pages/UserLoanPage/index.tsx
  src/pages/allProduct/index.tsx
  src/utils/cookieFn.ts
  src/utils/toasstify.ts
  yarn.lock
Labels: docs, feature

#110 발표 전 1차 배포 최종
  src/App.tsx
  src/api/axios.ts
  src/assets/Vector.svg
  src/assets/index.css
  src/assets/react.svg
  src/components/CartNLikePage/CartItem.tsx
  src/components/Header.tsx
  src/components/InfoSelect.tsx
  src/components/MainPage/GoodsList.tsx
  src/components/MainPage/ListBox.tsx
  src/components/MainPage/RecommendList.tsx
  src/components/MainPage/ToggleMenu/Agency.tsx
  src/components/MainPage/ToggleMenu/Location.tsx
  src/components/MainPage/ToggleMenu/Target.tsx
  src/components/MainPage/ToggleMenu/ToggleBody.tsx
  src/components/MainPage/ToggleMenu/ToggleHeader.tsx
  src/components/MainPage/ToggleMenu/Using.tsx
  src/components/MenuBar.tsx
  src/components/MyPage/LikeBox.tsx
  src/components/MyPage/LoanBox.tsx
  src/components/ProductDetail/Loan.tsx
  src/components/UserInfoPage/UserDetail.tsx
  src/components/UserInfoPage/UserInfo.tsx
  src/components/UserLoan/AccountDetail.tsx
  src/components/UserLoan/AccountHistory.tsx
  src/main.tsx
  src/pages/CartNLikesPage/index.tsx
  src/pages/CategoryPage/index.tsx
  src/pages/LoadingPage/index.tsx
  src/pages/MainPage/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/SearchPage/index.tsx
  src/pages/SignInPage/index.tsx
  src/pages/SignUpPage/index.tsx
  src/pages/UserInfoPage/PasswordCheck.tsx
  src/pages/UserInfoPage/index.tsx
  src/pages/UserLoanPage/index.tsx
  src/pages/allProduct/index.tsx
  src/utils/cookieFn.ts
  src/utils/toasstify.ts
  yarn.lock
Labels: feature
